### ISSUE TITLE
filter out tests in checkouts directories

### ISSUE THREAD

**Issue by mattflo-outpace** [jakemcc/lein-test-refresh#27]

**Comment by jakemcc** [comment]
If you add this to your project.clj then Leiningen will not add your checkouts' `:test-paths` to the classpath and `lein test-refresh` will no longer pick them up. It preserves `lein test-refresh` noticing changes to checkouts and refreshing then running your project's tests.

```clojure
:checkout-deps-shares ^:replace [:source-paths :resource-paths :compile-path
                                 #=(eval (var-get (find-var 'leiningen.core.classpath/checkout-deps-paths)))]
```

The `#=(eval...)` bit makes it work with nested checkouts.
