### ISSUE TITLE
Update clojure.tools.namespace to 0.2.10 to monitor .cljc files

### ISSUE THREAD

**Issue by viesti** [jakemcc/lein-test-refresh#29]
With the introduction of reader conditionals, there's a new type of clojure file (.cljc). clojure.tools.namespace version 0.2.10 detects these, so bumping this dependency would detect changes in .cljc files also.

**Comment by jakemcc** [comment]
Upgraded to 0.2.10 and released `[com.jakemccrary/lein-test-refresh 0.8.0]`. Thanks for pointing it out.
