### ISSUE TITLE
FR: show failing test stack traces at the bottom

### ISSUE THREAD

**Issue by yatesco** [jakemcc/lein-test-refresh#31]
First - thanks for the tool! 

Secondly, quickie has a really nice feature in that it shows the stack traces of failing tests at the bottom of the console. It would be great if lein-test-refresh did this.

As it stands I need to manually search for the FAIL error message which in a project with close to 10K unit tests and a whole bunch of logging isn't particularly fun ;).

Thanks!

**Comment by yatesco** [comment]
And I just noticed it now does this - is this a recent update? :).

**Comment by jakemcc** [comment]
@yatesco Not that I'm aware of. Glad to hear its doing what you want though :).
