### ISSUE TITLE
Improved output

### ISSUE THREAD

**Issue by donbonifacio** [jakemcc/lein-test-refresh#33]
We have a lot of test namespaces. This is our partial output:

![screen shot 2015-04-17 at 11 51 30](https://cloud.githubusercontent.com/assets/483669/7200779/2bc81164-e4f8-11e4-99a4-79675298cac7.png)

If the first namespace has an error, we will have to scroll that window to check it out. Suggestion: remove all the `Testing clanhr.directory-api.models.utils` outputs.

**Comment by jakemcc** [comment]
Yeah, I get a annoyed at all of the output as well. This is definitely a feature I'd like `lein-test-refresh` to support.

**Comment by jakemcc** [comment]
@donbonifacio Just released version `0.9.0` that adds support for suppressing the _Testing namespace_  output.

To enable it upgrade and add `:test-refresh {:quiet true}` someone in either your profiles.clj or your project.clj file. Example configuration can be found [here](https://github.com/jakemcc/lein-test-refresh/blob/master/sample.project.clj).

**Comment by donbonifacio** [comment]
@jakemcc just tried it, works great! Thanks! :)
This tools is great, I feel that I owe you. :)

**Comment by jakemcc** [comment]
@donbonifacio Awesome. Glad you're enjoying it. It has made a huge difference in my development style
