### ISSUE TITLE
more built in notification options

### ISSUE THREAD

**Issue by prozz** [jakemcc/lein-test-refresh#36]
hi. 

there is a :growl option, it would be nice to also have :terminal-notifier option out of the box.

thanks for writing this plugin!
PR

**Comment by jakemcc** [comment]
Hi there,

Glad to hear you're enjoying the plugin. Its a pretty important part of my workflow and its great to hear others are enjoying it.

I'm not going to add a `:terminal-notifier` option. The `:growl` is an artifact of it being implemented prior to the idea to allow specifying a customer `:notify-command`.

There is an example in the sample.project.clj for setting up `:notify-command` with terminal notifier. This is a great setting to be set in your global `profiles.clj`. Pretty easy to set it up once and never touch it again.

**Comment by prozz** [comment]
no probs. 

just thought sensible defaults for terminal notifier would be awesome, as :growl itself can be done by :notify-command too. :notify-command seem to add message as last param and this is something that breaks my imagined flow. for example, when using command 'say', id just like to have single word 'fail' not whole sentence about assertions etc. (also default red/green icons :))

best regards.
