### ISSUE TITLE
rerun just one namespace

### ISSUE THREAD

**Issue by thirdreplicator** [jakemcc/lein-test-refresh#41]
Is there a way to run just one namespace worth of tests at the command line like you can with

    lein test com.example.test-widgets

It would be nice if we could do

    lein test-refresh com.example.test-widgets

and have the tests keep running for that namespace.

**Comment by jakemcc** [comment]
Specifying a namespace currently isn't supported.

What you can do is add a `:test-selector` to your profiles.clj and then add metadata to the namespace you want to isolate.

If I want to do this I usually define a selector like `:test-selectors {:focused :focused}` in my project.clj. This allows me to add `^:focused` to `deftest` or `ns` forms and only run those tests in by running `lein test-refresh :focused`.

**Comment by thirdreplicator** [comment]
That sounds pretty convenient.   Do I have to restart (CTRL-C then lein
test-refresh) if I move the ^:focused meta data to another test?

**Comment by jakemcc** [comment]
Nope, it will pick up on the changed metadata and run whatever currently
matches the test selector function (in this case :focused)

You do have to start test refresh with the test selector you want to run
though.

I'd like to add a hardcoded keyword that could be used to move you from
running all your tests to running a subset of them but I just haven't
gotten around to it. I think it would be useful though.

**Comment by jakemcc** [comment]
Marking this as closed since it is mostly doable through `:test-selectors`
