### ISSUE TITLE
"Problem communicating with Growl"

### ISSUE THREAD

**Issue by heyarne** [jakemcc/lein-test-refresh#47]
I am getting the following error when trying to set up notifications:
`Problem communicating with growl, exception: Connection refused`

This happens when i run `lein test-refresh :growl` from the command line as well as when putting `:test-refresh {:growl true}` into my `project.clj`. Running on Mac OSX 10.10.5, Leiningen Version is 2.5.3, Java 1.8.0. lein-test-refresh is at version 0.12.0.

**Comment by heyarne** [comment]
Oooops my bad! I mistook growl for the built-in notification system of Mac OSX.

**Comment by jakemcc** [comment]
@heyarne No problem! 

If you want to use the built-in OS X notification then install `terminal-notifier` and add [this](https://github.com/jakemcc/lein-test-refresh/blob/master/sample.project.clj#L9) to your project.clj or profiles.clj.
