### ISSUE TITLE
Compatibility with jaycfields/expectations

### ISSUE THREAD

**Issue by julianjelfs** [jakemcc/lein-test-refresh#52]
Hi, 

Is there a specific reason that test-refresh doesn't work with https://github.com/jaycfields/expectations?

lein test works fine but lein test-refresh just doesn't seem to find any tests. 

It's not a huge problem, I don't have to use it, but if it's a simple fix it would be great. 

Thanks in advance. 

Julian. 

PS - I have a repo where you can see the problem if it helps: https://github.com/julianjelfs/agario3d

In here there are some tests inside game_test.clj and they are found by lein test but not by lein test-refresh.

**Comment by julianjelfs** [comment]
Ha - I just noticed your other project! auto-expect. I'm guessing that's what I need.

**Comment by jakemcc** [comment]
@julianjelfs Yep, autoexpect should do what you want.

For some background, `lein test` works with expectations because, by default, expectations run when the JVM shuts down.

In order to refresh and run tests, test-refresh and autoexpect need to know what function to call to trigger running tests.

**Comment by julianjelfs** [comment]
Great thanks! So much to learn.
