### ISSUE TITLE
fine-tuning the number of tests that get re-run

### ISSUE THREAD

**Issue by jdkealy** [jakemcc/lein-test-refresh#57]
Hi, 

I was wondering if fine-tuning the tests that get scheduled to run was on the roadmap. I have been running my test suite using 
      
    lein test-refresh :changes-only

And im finding myself have to go to great lengths to avoid including a namespace. For example, I have a queries file I use ubiquitously in all my tests for assertions. I'd like to somehow tell test-refresh to ignore certain tests even though the namespace is included in the test. 

Many thanks!

**Comment by jakemcc** [comment]
Hi @jdkealy,

You could achieve this by using test selectors to ignore namespaces or tests with certain metadata on them. lein-test-refresh supports a [subset of test selectors](https://github.com/jakemcc/lein-test-refresh/blob/master/CHANGES.md#040)

[Leiningen](https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#tests) points towards some more documentation about them.

From what you've described I think they would solve your problem.

Glad you're enjoying lein-test-refresh! Let me know if this doesn't help or you have more questions.
