### ISSUE TITLE
Enable calling `clojure.tools.namespace.repl/set-refresh-dirs` as part of setup.

### ISSUE THREAD

**Issue by grzm** [jakemcc/lein-test-refresh#59]
`.cljc` files in `/resources/` (such as those copied there during figwheel compilation) are picked up by default during `clojure.tools.namespace.repl/refresh`, which can stomp on code loaded into memory by `test-refresh`. By exposing `clojure.tools.namespace.repl/set-refresh-dirs` in some way as part of the test-refresh run, we can avoid this from happening.

For more detail, see [a blog post I wrote detailing how I worked around the same issue with the Reloaded workflow](http://seespotcode.net/2016/08/16/figwheel-reloaded/)

**Comment by grzm** [comment]
I believe this only needs to be called once, not on every test run. Perhaps have a "setup-fn" that's specified in project.clj and called in `leiningen.test-refresh/test-refresh`?

**Comment by jakemcc** [comment]
Interesting problem.

Allowing a generic `setup-fn` would allow `lein-test-refresh` users to do whatever they want (depending on implementationeither prior to every test run or just once before running any tests). That is an interesting approach as it would let people do whatever they want and I think would enable some neat things. If implemented for solving this problem it does put quite a burden on user of `lein-test-refresh`. I think the function would need to be called in the `com.jakemccrary.test-refresh/monitor-project` as that is when code is being evaluated within the context of the project.

Another approach would be to add a `:refresh-dirs` option that is similar to the `:watch-dirs` option. This feels a lot easier for users.

I won't be able to give a shot at either solution until sometime later this week. I'd most likely accept a PR for `:refresh-dirs` immediately. I'd need to think about the `setup-fn` idea a bit before getting that feature into the codebase.

**Comment by jakemcc** [comment]
Actually, was thinking about some weirdness I've been seeing in one of my own projects and wondering if its because of this problem. Going to build out the first option today.

**Comment by jakemcc** [comment]
Released `0.16.1-SNAPSHOT` with a `:refresh-dirs` option. Check the sample.project.clj for what it looks like.

Sort of wondering if :watch-dirs and :refresh-dirs should be collapsed into a single option. I'm having a difficult time coming up with a scenario in which you would set one and not the other.

**Comment by grzm** [comment]
Thanks! From my initial testing, setting `:refresh-dirs` with `0.16.1-SNAPSHOT` works for me!

I don't know enough about how Figwheel does its compilation, but I wonder if Figwheel could be convinced to place its compilation someplace other than where the final JavaScript output ends up. Of course that's an issue for a different project :)

Thanks again for your quick response!

**Comment by jakemcc** [comment]
Just released a non-snapshot release, `0.17.0`, with this feature.

**Comment by grzm** [comment]
Thanks!
