### ISSUE TITLE
run-once should exit with non-zero if there were test failures

### ISSUE THREAD

**Issue by awkay** [jakemcc/lein-test-refresh#64]
This line of code:

https://github.com/jakemcc/lein-test-refresh/blob/master/test-refresh/src/com/jakemccrary/test_refresh.clj#L285

is wrong. If the tests failed this should exit with 1, or else the plugin is not usable for running CI tests (e.g. for formatting with a custom formatter and run-once)

**Comment by jakemcc** [comment]
Fixed with pull request #65 .

Thanks!
