### ISSUE TITLE
test-refresh fails to start when project.clj has managed dependencies

### ISSUE THREAD

**Issue by jarppe** [jakemcc/lein-test-refresh#69]
The problem happens when `project.clj` has a managed dependency, like `[clj-time]`. If the dep is changed to non-managed `[clj-time "0.14.0"]` then everything works.

I have made a sample project that demonstrates the problem at https://github.com/jarppe/lein-test-refresh-issue

**What version of lein-test-refresh?**
0.20.0

**What version of Leiningen?**
2.7.1

**Can you recreate the issue with a minimal project?**
https://github.com/jarppe/lein-test-refresh-issue

**Comment by jakemcc** [comment]
Thanks for the great write up and example project. I've never used this feature of Leiningen before.

I'm about to leave on a trip but can try to sneak this in before. If not it won't be touched till mid-August.

**Comment by jakemcc** [comment]
@jarppe Just finished taking a look at this. Fixed the problem. I'll be releasing a new version later today. I'll post the updated version here.

**Comment by jakemcc** [comment]
`[com.jakemccrary/lein-test-refresh "0.21.0"]` released with a fix. Thanks for noticing it and making an example.
