### ISSUE TITLE
Feature request: circleci.test support

### ISSUE THREAD

**Issue by AndreTheHunter** [jakemcc/lein-test-refresh#72]
Please add support for https://github.com/circleci/circleci.test

**Comment by jakemcc** [comment]
@AndreTheHunter Seems like an interesting project, I'm surprised I haven't heard of it before.

Any feature of it that you're particularly interested in seeing work with lein-test-refresh? Is it the test runner?

I think some of the built-in reporters might work as is.

**Comment by AndreTheHunter** [comment]
I'd love the see the circleci.test runner work from within lein-test-refresh. I know circleci.test can be run multiple namespaces from the REPL using `(circleci.test/run-tests `, so lein-test-refresh would detect the affected namespaces and call this runner.

At the moment I'm using https://github.com/weavejester/lein-auto, but it's not ideal since it re-runs all the tests.

**Comment by jakemcc** [comment]
I just released version 0.22.0 of lein-test-refresh that detects if the circleci.test runner is available and then uses it.

[commit](https://github.com/jakemcc/lein-test-refresh/commit/1dfeb81f0734933cdd621137ccc3f23335f2b056)
