### ISSUE TITLE
test-refresh loads configuration for dev profile while running after a repl is started

### ISSUE THREAD

**Issue by anler** [jakemcc/lein-test-refresh#74]
**What version of lein-test-refresh?**

`0.22.0`

**What version of Leiningen?**

`Leiningen 2.8.1 on Java 1.8.0_152 Java HotSpot(TM) 64-Bit Server VM`

**Can you recreate the issue with a minimal project?**

[Link to project replicating the issue](https://github.com/anler/lein-test-refresh-example)

The issue is that, after starting `test-refresh` in the `test` profile, running a repl makes `test-refresh` to reload the project with the `dev` profile causing me issues, for example, such as running tests against the real database instead of the one used for testing.

**If you can't do above, can you share your project.clj and project structure?**

--

Thank you!

**Comment by anler** [comment]
After some further investigation, the issue is more with the integration with [cprop](https://github.com/tolitius/cprop), after running the repl cprop updates the `.lein-env` file with the `dev` profiles values causing the next run of `test-refresh` to use those instead of the `dev` ones.

**Comment by anler** [comment]
Issue fixed! I just needed to tell `cprop` to keep separated `.lein-env` files for each environment. I updated the project accordingly. Thank you!

**Comment by jakemcc** [comment]
@anler Just wanted to say thanks for bringing this up and digging into it. Very nice to come back from a vacation and see someone solve their own problem 😄 .

Thanks for using test-refresh!
