### ISSUE TITLE
Allow using custom keyword instead of :test-refresh/focus

### ISSUE THREAD

**Issue by metametadata** [jakemcc/lein-test-refresh#79]
The new `:test-refresh/focus` feature is very handy but it's tiresome to type this keyword every time. Would be helpful if it was shorter. E.g. by allowing customizing it in project.clj configuration:

```clj
:test-refresh {
  :focus-marker :myfocus
}
```

**Comment by jakemcc** [comment]
Thanks for the feedback. It is great to hear that it here are enjoying the
feature a lot too.

This seems like a reasonable request. I don't think I'll have the time to
implement it in the next week.

If you want it quicker, I'd be open to a PR.

**Comment by jakemcc** [comment]
This has been released in version 0.24.0. Check the readme and sample.project.clj for how to configure.

Thanks for the idea!
