### ISSUE TITLE
Running in Cursive REPL

### ISSUE THREAD

**Issue by klauswuestefeld** [jakemcc/lein-test-refresh#80]
I would like to refresh tests in a Cursive REPL so that I can navigate from stacktrace lines to source code. When I run lein test-refresh in a separate process there is no navigation.

After a couple of hours hacking I managed this:

```
(require 'com.jakemccrary.test-refresh)
(com.jakemccrary.test-refresh/monitor-project
  [(-> "test" java.io.File. .getCanonicalPath)]
  {:nses-and-selectors '[(my-test) [[(constantly true) ()]]]})
```

Could you provide an easier way?
The solution described here is good: https://github.com/jakemcc/lein-test-refresh/issues/38#issuecomment-110014874 I don't care that the REPL never returns.

I'm using lein-test-refresh version 0.23.0

Congrats on the project!
Thanks :)

**Comment by jakemcc** [comment]
Just wanted to say I started on making this easier while waiting for a
flight. Hopefully get something out in the next week or so

**Comment by klauswuestefeld** [comment]
Have a good flight!

**Comment by jakemcc** [comment]
[Released it](https://clojars.org/com.jakemccrary/lein-test-refresh). Readme.md has details.

**Comment by klauswuestefeld** [comment]
Using it :)
