### ISSUE TITLE
^:test-refresh/focus selector doesn't work in 0.24.0

### ISSUE THREAD

**Issue by takaczapka** [jakemcc/lein-test-refresh#82]
**What version of lein-test-refresh?**
0.24.0
**What version of Leiningen?**
2.9.1

It works ok with 0.23.0 version, so it looks like it's a regresshing

**Comment by jakemcc** [comment]
Uh oh, thanks for the report. I must have broken it and not realized it
sometime during the last release.

I think I have time in the next few days to look at this.

**Comment by jakemcc** [comment]
Fixed in 0.24.1 release. Sorry about that.
